services:
  apache:
    image: php:8.2-apache
    container_name: apache
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/.apache-config.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "80:80"
      - "444:443"
    depends_on:
      - mysql
    command: >
      /bin/bash -c "apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev 
      && docker-php-ext-configure gd --with-freetype --with-jpeg 
      && docker-php-ext-install mysqli pdo pdo_mysql gd 
      && a2enmod rewrite 
      && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
